export class Personal {
    cedula:string;
    nombre:string;
    apellidos:string;
    telefono:string;
    nacimiento:string;
    direccion:string;
    ingreso:string;
    puesto:string;
    contrasena:string;
    constructor(cedula,nombre,apellidos,telefono,nacimiento,direccion,ingreso,puesto,contrasena){
        this.cedula=cedula;
        this.nombre=nombre;
        this.apellidos=apellidos;
        this.telefono=telefono;
        this.nacimiento=nacimiento;
        this.direccion=direccion;
        this.ingreso=ingreso;
        this.puesto=puesto;
        this.contrasena=contrasena;
    }
}
